### ISSUE TITLE
Mobile configuration fields are out of sync with the proposal

### ISSUE THREAD

**Issue by wtrocki** [aerogear/mobile-cli#73]
For example: `clusterName` => `cluster_name`.
Version should be number but it's added as string. etc.

Using `clusterName` makes forces mobile SDK to write custom parser, while having `clusterName` will work out of the box.

See: 
https://github.com/aerogear/proposals/blob/master/sdks/Mobile-configuration.md

**Comment by wtrocki** [comment]
ping @maleck13

**Comment by maleck13** [comment]
Thanks @wtrocki will take a look at these
