### ISSUE TITLE
Remove Client ID from generated Keycloak Config

### ISSUE THREAD

**Issue by TommyJ1994** [aerogear/mobile-cli#88]
The Keycloak config outputs a `clientid` in the config. Keycloak uses the `resource` keyword instead for referencing Clients in its adapters. The resource key is already here, so we can remove the clientID reference.

```
"config": {
				"auth-server-url": "https://keycloak-noop.192.168.37.1.nip.io/auth",
				"clientId": "RjevWDrtcSTZeDwhoYnS",
				"realm": "noop",
				"resource": "RjevWDrtcSTZeDwhoYnS",
				"ssl-required": "external",
				"url": "https://keycloak-noop.192.168.37.1.nip.io/auth"
			},
```

**Comment by aidenkeating** [comment]
Keeping track of the required changes, each change is quite small though

* [x] Android SDK Example App (https://github.com/aerogear/aerogear-android-sdk/pull/181)
* [ ] Android Showcase App
* [x] iOS SDK Example App (https://github.com/aerogear/aerogear-ios-sdk/pull/70)
* [ ] iOS Showcase App
* [x] Keycloak APB (https://github.com/aerogearcatalog/keycloak-apb/pull/66)

**Comment by aidenkeating** [comment]
Closing this as `clientId` is no longer generated and has been removed from `mobile-services.json` files.
